# overlays/production/patch.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  parallelism: "10"
  workflowEvents: |
    enabled: false
  workflowDefaults: |
    metadata:
      annotations: 
        argo: workflows
    spec:
      ttlStrategy:
        secondsAfterSuccess: 3600
      parallelism: 3
      serviceAccountName: cluster-workflow-executor

  
