apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging

resources:
- ../../base
# - kubelet.clusterinput.yaml
- containers.clusterinput.yaml
- kubernetes.clusterfilter.yaml
- victoria-logs.clusteroutput.yaml
- fluent-bit-config.clusterfluentbitconfig.yaml
- fluent-bit.fluentbit.yaml

images:
  - name: ghcr.io/fluent/fluent-operator/fluent-bit
    newTag: v4.2.2